### ISSUE TITLE
Blakley and Shamir shared secret algorithms are orderless

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#6]
As far as I know, both Blakley and Shamir shared secret algorithms are orderless.
So I think that 

```java
public class KeyPartEntity {
        ...
	public int order;
        ...
}
```

is useless in this case. Or maybe it's different "order"? Comments in code, are highly welcome.

**Comment by PatrykMilewski** [comment]
There is link to this class file:
https://github.com/RaspberryWallet/Backend/blob/master/Manager/src/main/java/io/raspberrywallet/manager/database/KeyPartEntity.java

Yes, it is useless. 

Actually I think this class needs some refactor, since there are different level of abstractions in the same method, which makes it hard to read. Also Lombok annotations should be outside of the class and method name "clean" should be called "destroy" and maybe we should think about making destroyable interface, which will be implemented by this. It will cause less dependencies in code, since in many situations there will be only single call:
```
Destroyable key = new KeyPartEntity();
key.destroy();
```

**Comment by stanbar** [comment]
If `order` is the indicator of key portion to decrypt, then I don't think that just `order` as an `index` is sufficient in our case.

**Comment by PatrykMilewski** [comment]
is it fixed?

**Comment by PatrykMilewski** [comment]
after meeting we agreed to call this:

**order**
