### ISSUE TITLE
Java Serialization in cryptography

### ISSUE THREAD

**Issue by stanbar** [RaspberryWallet/Backend#66]
Could you please exaplain why do we need to involve Java Serialization to our cryptography ?
For example:
```java
    @Override
public byte[] encrypt(byte[] payload) throws RequiredInputNotFound, EncryptionException {
        Password password = new Password(getPin());
    
        AESEncryptedObject<ByteWrapper> encryptedObject =
                CryptoObject.encrypt(new ByteWrapper(payload), password);
        
        return SerializationUtils.serialize(encryptedObject);
```
I don't get why the API looks like this, and not just 
```java
    @Override
public byte[] encrypt(byte[] payload) throws RequiredInputNotFound, EncryptionException {
        Password password = new Password(getPin());
        return CryptoObject.encrypt(new ByteWrapper(payload), password);
```

**Comment by PatrykMilewski** [comment]
Well, we can use `CryptoStream` instead, but using `CryptoObject` is shorter/easier.

It's simple idea:
1. You wrap your data in any wrapper, or you can just pass Object, that implements Serializable, so it would be simpler. For byte arrays I made ByteWrapper.
2. Now you can simply encrypt your object (since CryptoObject accepts any Object, that impements Serializable) and in return, you get wrapped encrypted bytes with `AESEncryptedObject` class, that holds all the info about used parameters for AES.
3. Since we have to return byte array, then we can just Serialize `AESEncryptedObject` wrapper with encrypted data inside it and return this.

I see the problem, that it uses Serialization, which is generally slow and unwanted. The better way would be to use `CryptoStream` instead, but to be honest, tests of these were lost somewhere and I couldn't get it to work and then used `CryptoObject`.

**Comment by PatrykMilewski** [comment]
The API looks like this, because it was took from BSK project, where AESEncryptedObjects was stored in collection, so there was no point in returning byte array.

**Comment by stanbar** [comment]
Ok, thanks. I get it 👍
